 /********************************************************************************************************************************
 * Module: Port
 *
 * File Name: PORT_PBcfg.c
 *
 * Description: Source file for PORT PostBuild Configuration
 *
 * Author: Ahmad Shabrawy
 ********************************************************************************************************************************/


/*Module SW Version (1.0.0)*/

#define PORT_PBCFG_SW_MAJOR_VERSION				(1U)
#define PORT_PBCFG_SW_MINOR_VERSION				(0U)
#define PORT_PBCFG_SW_PATCH_VERSION				(0U)

/*Module AUTOSAR Version (4.0.3)*/

#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION				(4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION				(0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION				(3U)


#include"Port.h"

/*AUTOSAR Checking between Port_PBcfg.h and Port.h*/
#if ((PORT_AR_RELEASE_MAJOR_VERSION != PORT_PBCFG_AR_RELEASE_MAJOR_VERSION)\
		||(PORT_AR_RELEASE_MINOR_VERSION != PORT_PBCFG_AR_RELEASE_MINOR_VERSION)\
		||(PORT_AR_RELEASE_PATCH_VERSION != PORT_PBCFG_AR_RELEASE_PATCH_VERSION))
#error "The AUTOSAR version of Port.h doesn't match the expected version"
#endif

/*SW Checking between Port_PBcfg.h and Port.h*/
#if ((PORT_SW_MAJOR_VERSION != PORT_PBCFG_SW_MAJOR_VERSION)\
		||(PORT_SW_MINOR_VERSION != PORT_PBCFG_SW_MINOR_VERSION)\
		||(PORT_SW_PATCH_VERSION != PORT_PBCFG_SW_PATCH_VERSION))
#error "The Software version of Port.h doesn't match the expected version"
#endif

/*Post_Build Struct used with Port_Init API*/

const Port_ConfigType Port_Configuration = {
		{
	{PORT_A_PIN_0_DIRECTION, PORT_A_PIN_0_RESISTOR_MODE, PORT_A_PIN_0_LEVEL_VALUE, PORT_A_PIN_0, PORT_A_NUM, PORT_A_PIN_0_INITIAL_MODE, PORT_A_PIN_0_DIRECTION_CHANGEABLE, PORT_A_PIN_0_MODE_CHANGEABLE},
	{PORT_A_PIN_1_DIRECTION, PORT_A_PIN_1_RESISTOR_MODE, PORT_A_PIN_1_LEVEL_VALUE, PORT_A_PIN_1, PORT_A_NUM, PORT_A_PIN_1_INITIAL_MODE, PORT_A_PIN_1_DIRECTION_CHANGEABLE, PORT_A_PIN_1_MODE_CHANGEABLE},
	{PORT_A_PIN_2_DIRECTION, PORT_A_PIN_2_RESISTOR_MODE, PORT_A_PIN_2_LEVEL_VALUE, PORT_A_PIN_2, PORT_A_NUM, PORT_A_PIN_2_INITIAL_MODE, PORT_A_PIN_2_DIRECTION_CHANGEABLE, PORT_A_PIN_2_MODE_CHANGEABLE},
	{PORT_A_PIN_3_DIRECTION, PORT_A_PIN_3_RESISTOR_MODE, PORT_A_PIN_3_LEVEL_VALUE, PORT_A_PIN_3, PORT_A_NUM, PORT_A_PIN_3_INITIAL_MODE, PORT_A_PIN_3_DIRECTION_CHANGEABLE, PORT_A_PIN_3_MODE_CHANGEABLE},
	{PORT_A_PIN_4_DIRECTION, PORT_A_PIN_4_RESISTOR_MODE, PORT_A_PIN_4_LEVEL_VALUE, PORT_A_PIN_4, PORT_A_NUM, PORT_A_PIN_4_INITIAL_MODE, PORT_A_PIN_4_DIRECTION_CHANGEABLE, PORT_A_PIN_4_MODE_CHANGEABLE},
	{PORT_A_PIN_5_DIRECTION, PORT_A_PIN_5_RESISTOR_MODE, PORT_A_PIN_5_LEVEL_VALUE, PORT_A_PIN_5, PORT_A_NUM, PORT_A_PIN_5_INITIAL_MODE, PORT_A_PIN_5_DIRECTION_CHANGEABLE, PORT_A_PIN_5_MODE_CHANGEABLE},
	{PORT_A_PIN_6_DIRECTION, PORT_A_PIN_6_RESISTOR_MODE, PORT_A_PIN_6_LEVEL_VALUE, PORT_A_PIN_6, PORT_A_NUM, PORT_A_PIN_6_INITIAL_MODE, PORT_A_PIN_6_DIRECTION_CHANGEABLE, PORT_A_PIN_6_MODE_CHANGEABLE},
	{PORT_A_PIN_7_DIRECTION, PORT_A_PIN_7_RESISTOR_MODE, PORT_A_PIN_7_LEVEL_VALUE, PORT_A_PIN_7, PORT_A_NUM, PORT_A_PIN_7_INITIAL_MODE, PORT_A_PIN_7_DIRECTION_CHANGEABLE, PORT_A_PIN_7_MODE_CHANGEABLE},


	{PORT_B_PIN_0_DIRECTION, PORT_B_PIN_0_RESISTOR_MODE, PORT_B_PIN_0_LEVEL_VALUE, PORT_B_PIN_0, PORT_B_NUM, PORT_B_PIN_0_INITIAL_MODE, PORT_B_PIN_0_DIRECTION_CHANGEABLE, PORT_B_PIN_0_MODE_CHANGEABLE},
	{PORT_B_PIN_1_DIRECTION, PORT_B_PIN_1_RESISTOR_MODE, PORT_B_PIN_1_LEVEL_VALUE, PORT_B_PIN_1, PORT_B_NUM, PORT_B_PIN_1_INITIAL_MODE, PORT_B_PIN_1_DIRECTION_CHANGEABLE, PORT_B_PIN_1_MODE_CHANGEABLE},
	{PORT_B_PIN_2_DIRECTION, PORT_B_PIN_2_RESISTOR_MODE, PORT_B_PIN_2_LEVEL_VALUE, PORT_B_PIN_2, PORT_B_NUM, PORT_B_PIN_2_INITIAL_MODE, PORT_B_PIN_2_DIRECTION_CHANGEABLE, PORT_B_PIN_2_MODE_CHANGEABLE},
	{PORT_B_PIN_3_DIRECTION, PORT_B_PIN_3_RESISTOR_MODE, PORT_B_PIN_3_LEVEL_VALUE, PORT_B_PIN_3, PORT_B_NUM, PORT_B_PIN_3_INITIAL_MODE, PORT_B_PIN_3_DIRECTION_CHANGEABLE, PORT_B_PIN_3_MODE_CHANGEABLE},
	{PORT_B_PIN_4_DIRECTION, PORT_B_PIN_4_RESISTOR_MODE, PORT_B_PIN_4_LEVEL_VALUE, PORT_B_PIN_4, PORT_B_NUM, PORT_B_PIN_4_INITIAL_MODE, PORT_B_PIN_4_DIRECTION_CHANGEABLE, PORT_B_PIN_4_MODE_CHANGEABLE},
	{PORT_B_PIN_5_DIRECTION, PORT_B_PIN_5_RESISTOR_MODE, PORT_B_PIN_5_LEVEL_VALUE, PORT_B_PIN_5, PORT_B_NUM, PORT_B_PIN_5_INITIAL_MODE, PORT_B_PIN_5_DIRECTION_CHANGEABLE, PORT_B_PIN_5_MODE_CHANGEABLE},
	{PORT_B_PIN_6_DIRECTION, PORT_B_PIN_6_RESISTOR_MODE, PORT_B_PIN_6_LEVEL_VALUE, PORT_B_PIN_6, PORT_B_NUM, PORT_B_PIN_6_INITIAL_MODE, PORT_B_PIN_6_DIRECTION_CHANGEABLE, PORT_B_PIN_6_MODE_CHANGEABLE},
	{PORT_B_PIN_7_DIRECTION, PORT_B_PIN_7_RESISTOR_MODE, PORT_B_PIN_7_LEVEL_VALUE, PORT_B_PIN_7, PORT_B_NUM, PORT_B_PIN_7_INITIAL_MODE, PORT_B_PIN_7_DIRECTION_CHANGEABLE, PORT_B_PIN_7_MODE_CHANGEABLE},

	{PORT_C_PIN_0_DIRECTION, PORT_C_PIN_0_RESISTOR_MODE, PORT_C_PIN_0_LEVEL_VALUE, PORT_C_PIN_0, PORT_C_NUM, PORT_C_PIN_0_INITIAL_MODE, PORT_C_PIN_0_DIRECTION_CHANGEABLE, PORT_C_PIN_0_MODE_CHANGEABLE},
	{PORT_C_PIN_1_DIRECTION, PORT_C_PIN_1_RESISTOR_MODE, PORT_C_PIN_1_LEVEL_VALUE, PORT_C_PIN_1, PORT_C_NUM, PORT_C_PIN_1_INITIAL_MODE, PORT_C_PIN_1_DIRECTION_CHANGEABLE, PORT_C_PIN_1_MODE_CHANGEABLE},
	{PORT_C_PIN_2_DIRECTION, PORT_C_PIN_2_RESISTOR_MODE, PORT_C_PIN_2_LEVEL_VALUE, PORT_C_PIN_2, PORT_C_NUM, PORT_C_PIN_2_INITIAL_MODE, PORT_C_PIN_2_DIRECTION_CHANGEABLE, PORT_C_PIN_2_MODE_CHANGEABLE},
	{PORT_C_PIN_3_DIRECTION, PORT_C_PIN_3_RESISTOR_MODE, PORT_C_PIN_3_LEVEL_VALUE, PORT_C_PIN_3, PORT_C_NUM, PORT_C_PIN_3_INITIAL_MODE, PORT_C_PIN_3_DIRECTION_CHANGEABLE, PORT_C_PIN_3_MODE_CHANGEABLE},
	{PORT_C_PIN_4_DIRECTION, PORT_C_PIN_4_RESISTOR_MODE, PORT_C_PIN_4_LEVEL_VALUE, PORT_C_PIN_4, PORT_C_NUM, PORT_C_PIN_4_INITIAL_MODE, PORT_C_PIN_4_DIRECTION_CHANGEABLE, PORT_C_PIN_4_MODE_CHANGEABLE},
	{PORT_C_PIN_5_DIRECTION, PORT_C_PIN_5_RESISTOR_MODE, PORT_C_PIN_5_LEVEL_VALUE, PORT_C_PIN_5, PORT_C_NUM, PORT_C_PIN_5_INITIAL_MODE, PORT_C_PIN_5_DIRECTION_CHANGEABLE, PORT_C_PIN_5_MODE_CHANGEABLE},
	{PORT_C_PIN_6_DIRECTION, PORT_C_PIN_6_RESISTOR_MODE, PORT_C_PIN_6_LEVEL_VALUE, PORT_C_PIN_6, PORT_C_NUM, PORT_C_PIN_6_INITIAL_MODE, PORT_C_PIN_6_DIRECTION_CHANGEABLE, PORT_C_PIN_6_MODE_CHANGEABLE},
	{PORT_C_PIN_7_DIRECTION, PORT_C_PIN_7_RESISTOR_MODE, PORT_C_PIN_7_LEVEL_VALUE, PORT_C_PIN_7, PORT_C_NUM, PORT_C_PIN_7_INITIAL_MODE, PORT_C_PIN_7_DIRECTION_CHANGEABLE, PORT_C_PIN_7_MODE_CHANGEABLE},


	{PORT_D_PIN_0_DIRECTION, PORT_D_PIN_0_RESISTOR_MODE, PORT_D_PIN_0_LEVEL_VALUE, PORT_D_PIN_0, PORT_D_NUM, PORT_D_PIN_0_INITIAL_MODE, PORT_D_PIN_0_DIRECTION_CHANGEABLE, PORT_D_PIN_0_MODE_CHANGEABLE},
	{PORT_D_PIN_1_DIRECTION, PORT_D_PIN_1_RESISTOR_MODE, PORT_D_PIN_1_LEVEL_VALUE, PORT_D_PIN_1, PORT_D_NUM, PORT_D_PIN_1_INITIAL_MODE, PORT_D_PIN_1_DIRECTION_CHANGEABLE, PORT_D_PIN_1_MODE_CHANGEABLE},
	{PORT_D_PIN_2_DIRECTION, PORT_D_PIN_2_RESISTOR_MODE, PORT_D_PIN_2_LEVEL_VALUE, PORT_D_PIN_2, PORT_D_NUM, PORT_D_PIN_2_INITIAL_MODE, PORT_D_PIN_2_DIRECTION_CHANGEABLE, PORT_D_PIN_2_MODE_CHANGEABLE},
	{PORT_D_PIN_3_DIRECTION, PORT_D_PIN_3_RESISTOR_MODE, PORT_D_PIN_3_LEVEL_VALUE, PORT_D_PIN_3, PORT_D_NUM, PORT_D_PIN_3_INITIAL_MODE, PORT_D_PIN_3_DIRECTION_CHANGEABLE, PORT_D_PIN_3_MODE_CHANGEABLE},
	{PORT_D_PIN_4_DIRECTION, PORT_D_PIN_4_RESISTOR_MODE, PORT_D_PIN_4_LEVEL_VALUE, PORT_D_PIN_4, PORT_D_NUM, PORT_D_PIN_4_INITIAL_MODE, PORT_D_PIN_4_DIRECTION_CHANGEABLE, PORT_D_PIN_4_MODE_CHANGEABLE},
	{PORT_D_PIN_5_DIRECTION, PORT_D_PIN_5_RESISTOR_MODE, PORT_D_PIN_5_LEVEL_VALUE, PORT_D_PIN_5, PORT_D_NUM, PORT_D_PIN_5_INITIAL_MODE, PORT_D_PIN_5_DIRECTION_CHANGEABLE, PORT_D_PIN_5_MODE_CHANGEABLE},
	{PORT_D_PIN_6_DIRECTION, PORT_D_PIN_6_RESISTOR_MODE, PORT_D_PIN_6_LEVEL_VALUE, PORT_D_PIN_6, PORT_D_NUM, PORT_D_PIN_6_INITIAL_MODE, PORT_D_PIN_6_DIRECTION_CHANGEABLE, PORT_D_PIN_6_MODE_CHANGEABLE},
	{PORT_D_PIN_7_DIRECTION, PORT_D_PIN_7_RESISTOR_MODE, PORT_D_PIN_7_LEVEL_VALUE, PORT_D_PIN_7, PORT_D_NUM, PORT_D_PIN_7_INITIAL_MODE, PORT_D_PIN_7_DIRECTION_CHANGEABLE, PORT_D_PIN_7_MODE_CHANGEABLE},

		}
			};


